sudo: false
language: node_js
node_js:
  - "5.6.0"

git:
  submodules: false

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm update -g npm
  - npm install
  - npm test
